### ISSUE TITLE
Receiving not working after entering background mode

### ISSUE THREAD

**Issue by adarshjayan7574** [chirp/chirp-ios-examples#10]
When i resumes the example application from background to foreground chirp stops receiving the data, only sending part is working. This issue is only with iPad devices, same case for iphone is working.

Note : When audio background capability is enabled  receiving starts working.

Tested device - ipad Mini
OS - iOS 11.0.2
Protocol - Ultrasonic
Code - https://github.com/chirp/chirp-ios-examples/tree/master/Swift/Messenger

**Comment by joextodd** [comment]
Do you see any console errors when resuming from the background?

**Comment by joextodd** [comment]
With the help of another user, I have been able to reproduce the issue on an iPhone 7 running iOS 12.2.

It looks like upgrading to the latest SDK will fix the issue, see https://github.com/chirp/chirp-ios-examples/pull/14

Please re open this issue if it does not.
