### ISSUE TITLE
Thread operation

### ISSUE THREAD

**Issue by askquickly** [chirp/chirp-ios-examples#11]
PayPal[42354:6393913] [Animation] +[UIView setAnimationsEnabled:] being called from a background thread. Performing any operation from a background thread on UIView or a subclass is not supported and may result in unexpected and insidious behavior.

Click on receive then the crash happens

**Comment by joextodd** [comment]
@askquickly could you provide a little more detail on how to reproduce this bug? We are not using `setAnimationsEnabled` at all in the example repos.
